name: campus_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0'

dependencies:
  cached_network_image: ^3.2.3
  connectivity_plus: ^4.0.1
  device_info_plus: ^9.0.2
  dio: ^5.1.2
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_secure_storage: ^8.0.0
  geolocator: ^9.0.2
  hive: ^2.2.3
  http: ^0.13.5
  intl: ^0.18.1
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  package_info_plus: ^4.0.2
  path_provider: ^2.0.15
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  sliding_up_panel: ^2.0.0+1
  syncfusion_flutter_calendar: ^21.2.4
  syncfusion_flutter_charts: ^21.1.41
  url_launcher: ^6.1.10
  xml: ^6.2.2
  xml2json: ^6.1.0
  barcode_widget: ^2.0.4
  lottie: ^2.3.2
  shared_preferences: ^2.1.2
  flutter_riverpod: ^2.3.6
  get_it: ^7.6.0
  collection: ^1.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.1
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  lints: ^2.1.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/map_styles/
    - assets/images/logos/tum-logo-blue.png
    - assets/images/logos/tum-logo-rainbow.png
    - assets/images/Portrait_Placeholder.png
    - assets/images/movie_placeholder.png
    - assets/lottieFiles/gradient_background_blue_red.json
    - assets/lottieFiles/gradient_background_blue_white.json
    - assets/lottieFiles/gradient_background_blue_white_speedup.json
    - assets/lottieFiles/gradient_background_silver_white.json