name: campus_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.3.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  connectivity_plus: ^5.0.0
  device_info_plus: ^10.0.0
  dio: ^5.1.2
  dio_cache_interceptor: ^3.4.2
  dio_cache_interceptor_hive_store: ^3.2.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_secure_storage: ^9.0.0
  geolocator: ^10.0.1
  hive: ^2.2.3
  http: ^0.13.6
  intl: any
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  package_info_plus: ^5.0.0
  path_provider: ^2.0.15
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  syncfusion_flutter_calendar: ^23.1.36
  syncfusion_flutter_charts: ^23.1.36
  url_launcher: ^6.1.10
  video_player: ^2.6.1
  xml: ^6.2.2
  xml2json: ^6.1.0
  barcode_widget: ^2.0.4
  lottie: ^2.3.2
  shared_preferences: ^2.1.2
  flutter_riverpod: ^2.3.6
  get_it: ^7.6.0
  collection: ^1.17.2
  timeago: ^3.4.0
  webview_flutter: ^4.2.2
  flutter_launcher_icons: ^0.13.1
  # connecting with the tca-backend
  grpc: ^3.2.4
  protobuf: ^3.0.0
  fixnum: any
  tflite_flutter: ^0.10.1
  syncfusion_flutter_datepicker: ^23.1.36
  google_maps_flutter: ^2.4.0
  uuid: ^3.0.7
  flutter_map: ^4.0.0
  latlong2: ^0.8.2
  flutter_svg: ^2.0.7
  map_launcher: ^2.5.0+1
  flutter_staggered_grid_view: ^0.7.0
  flutter_localizations:
    sdk: flutter

dependency_overrides:
  xml2json:
    git:
      url: https://github.com/jakobkoerber/xml2json.git
      ref: master
  grpc:
    git:
      url: https://github.com/jakobkoerber/grpc-dart.git
      ref: master
  google_maps_flutter_ios:
    git:
      url: https://github.com/jakobkoerber/packages.git
      path: packages/google_maps_flutter/google_maps_flutter_ios
      ref: main
  tflite_flutter: 0.10.1
  package_info_plus: 4.1.0
  device_info_plus: 9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.3
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  lints: ^2.1.1
  dart_code_metrics: ^5.7.6

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/mapStyles/
    - assets/images/logos/tum-logo-blue.png
    - assets/images/logos/tum-logo-rainbow.png
    - assets/images/placeholders/portrait_placeholder.png
    - assets/images/placeholders/movie_placeholder.png
    - assets/images/placeholders/news_placeholder.png
    - assets/images/errors/error.png
    - assets/images/errors/error_crop.png
    - assets/images/errors/error_square.png
    - assets/lottieFiles/gradient_background_blue_red.json
    - assets/lottieFiles/gradient_background_blue_white.json
    - assets/lottieFiles/gradient_background_blue_white_speedup.json
    - assets/lottieFiles/gradient_background_silver_white.json
    - assets/images/tower.png
    - assets/videos/token-tutorial.mp4
    - assets/images/campus/campus-freising.jpg
    - assets/images/campus/campus-garching.jpeg
    - assets/images/campus/campus-klinikum.jpg
    - assets/images/campus/campus-olympia.jpg
    - assets/images/campus/campus-stamm.jpeg
    - assets/models/english_bert_30.tflite