name: campus_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 5.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # networking
  dio: ^5.1.2
  # dio_cache_interceptor: ^3.5.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  cached_network_image: ^3.2.3
  grpc: ^3.2.4
  protobuf: ^3.0.0
  xml: ^6.2.2
  xml2json: ^6.1.0

  # state management
  rxdart: ^0.27.7
  go_router: ^13.2.0
  flutter_riverpod: ^2.3.6
  get_it: ^7.6.0

  # user interface
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.9
  flutter_linkify: ^6.0.0
  home_widget: ^0.4.1
  auto_size_text: ^3.0.0
  quick_actions: ^1.0.7
  flutter_native_splash: ^2.2.19
  syncfusion_flutter_calendar: "24.2.4"
  syncfusion_flutter_charts: "24.2.9"
  syncfusion_flutter_datepicker: "24.2.9"
  google_maps_flutter: ^2.5.3
  video_player: ^2.6.1
  barcode_widget: ^2.0.4
  lottie: ^3.0.0
  timeago: ^3.4.0

  # helpers
  device_info_plus: ^9.1.1
  flutter_secure_storage: ^9.0.0
  geolocator: ^11.0.0
  package_info_plus: ^5.0.0
  path_provider: ^2.0.15
  url_launcher: ^6.1.10
  permission_handler: ^11.1.0
  uuid: ^4.2.1
  collection: ^1.18.0
  shared_preferences: ^2.1.2
  map_launcher: ^3.0.1

  # firebase
  firebase_crashlytics: ^3.4.6
  firebase_core: ^2.24.0

  # localization
  flutter_localizations:
    sdk: flutter
  intl: any

dependency_overrides:
  xml2json:
    git:
      url: https://github.com/jakobkoerber/xml2json.git
      ref: master
  grpc:
    git:
      url: https://github.com/jakobkoerber/grpc-dart.git
      ref: master
  google_maps_flutter_ios:
    git:
      url: https://github.com/jakobkoerber/packages.git
      path: packages/google_maps_flutter/google_maps_flutter_ios
      ref: main

dev_dependencies:
  # code generation
  build_runner: ^2.3.3
  isar_generator: ^3.1.0+1

  # testing
  flutter_test:
    sdk: flutter
  test: ^1.24.3

  # linting
  flutter_lints: ^3.0.0
  lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/mapStyles/
    - assets/images/logos/tum-logo-blue.png
    - assets/images/logos/tum-logo-blue-text.png
    - assets/images/logos/tum-logo-rainbow.png
    - assets/images/placeholders/portrait_placeholder.png
    - assets/images/placeholders/movie_placeholder.png
    - assets/images/placeholders/news_placeholder.png
    - assets/images/errors/error.svg
    - assets/lottieFiles/gradient_background_blue_red.json
    - assets/lottieFiles/gradient_background_blue_white.json
    - assets/lottieFiles/gradient_background_blue_white_speedup.json
    - assets/lottieFiles/gradient_background_silver_white.json
    - assets/images/tower.png
    - assets/videos/token-tutorial.mp4
    - assets/images/campus/campus-freising.jpg
    - assets/images/campus/campus-garching.jpeg
    - assets/images/campus/campus-klinikum.jpg
    - assets/images/campus/campus-olympia.jpg
    - assets/images/campus/campus-stamm.jpeg
    - assets/images/location.png
