on:
  push:
    branches:
      - 'development'

jobs:
  deploy:
    runs-on: macos-latest

    strategy:
      matrix:
        platform: [ android ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Install Bundle
        run: cd ./${{ matrix.platform }} && bundle install

      - name: Deploy to Google Play Store
        run: |
          cd ./android
          bundle exec fastlane test
        env:
          GOOGLE_PLAY_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_KEY }}